[package]
name = "openlate-codegen"
version = "0.1.0"
edition = "2021"
exclude = ["metadata/*.md", "*.py", "**/__pycache__", "**.mako", "**.pyc", "**.proto"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openlate-sys ={ path = "../openlate-sys"}
tera = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
